package com.zure.localaiengine.core.inference

enum class InferenceTask {
    IMAGE_CLASSIFICATION,
    OBJECT_DETECTION,
    IMAGE_SEGMENTATION,
    OCR,
    TEXT_GENERATION,
    TEXT_EMBEDDING,
    TEXT_TO_SPEECH,
    VISION_LANGUAGE,
    AUDIO_TRANSCRIPTION,
    MULTIMODAL_GENERATION,
    TENSOR
}
